# Introduction

## What is Data Analysis?
Data analysis is a process of inspecting, cleansing, transforming, and modeling data with the goal of discovering useful information, informing conclusions, and supporting decision-making.


**long story short.........**

![torture](torture1.jpg)


## Torture
**<center><span class="mark">Data analysis is torturing you data till it starts giving result</span></center>**


![torture](torture2.jpg)

<center>**Something like that**</center>

# Can we start coding already?

## What we will cover
* Exploring arrays with NumPy
* Handling data with pandas

if there is more time
* Reading and writing data from various formats
* Handling missing data

## Dataset
Generate random age

In [2]:
num = [28, 30, 31, 33, 19, 26, 25, 26, 37, 22, 37, 24, 21, 32, 31, 33, 34,
       40, 38, 32, 36, 32, 23, 20, 30, 42, 20, 37, 21, 27, 25, 40, 24, 39,
       25, 23, 32, 25, 21, 41, 34, 40, 31, 33, 32, 31, 18, 18, 42, 29]

# Numpy


## Why numpy?

Python list on its own is not suitable to perform heavy mathematical operations, as it is not optimized for it.

Numpy is created fundamentally for scientific computing. It helps handle large multidimensional arrays and matrices, along with a large library of high-level mathematical functions to operate on these arrays.

A NumPy array would require much less memory to store the same amount of data compared to a Python list, which helps in reading and writing from the array in a faster manner.

## Import numpy
Import libraries and write settings here.

In [3]:
# Data manipulation
import numpy as np

## Creating a numpy array

In [4]:
age = np.array(num)
age

array([28, 30, 31, 33, 19, 26, 25, 26, 37, 22, 37, 24, 21, 32, 31, 33, 34,
       40, 38, 32, 36, 32, 23, 20, 30, 42, 20, 37, 21, 27, 25, 40, 24, 39,
       25, 23, 32, 25, 21, 41, 34, 40, 31, 33, 32, 31, 18, 18, 42, 29])

## Dimension
`ndim` output the number of dimensions of an array 

In [5]:
example = np.array([[1,2,3],
                   [3,4,5],
                   [6,7,8]])

In [6]:
example.ndim

2

In [7]:
age.ndim

1

## Shape
output the size of the dimension

In [8]:
example.shape

(3, 3)

In [9]:
age.shape

(50,)

In [10]:
example.size

9

In [11]:
age.size

50

## Mathematical operations

In [12]:
age + 2


array([30, 32, 33, 35, 21, 28, 27, 28, 39, 24, 39, 26, 23, 34, 33, 35, 36,
       42, 40, 34, 38, 34, 25, 22, 32, 44, 22, 39, 23, 29, 27, 42, 26, 41,
       27, 25, 34, 27, 23, 43, 36, 42, 33, 35, 34, 33, 20, 20, 44, 31])

## Trigonometric function

In [13]:
np.sin(example)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

## Conditional operations

In [14]:
age>35

array([False, False, False, False, False, False, False, False,  True,
       False,  True, False, False, False, False, False, False,  True,
        True, False,  True, False, False, False, False,  True, False,
        True, False, False, False,  True, False,  True, False, False,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False,  True, False])

## Indexing and slice

In [15]:
example

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

### Index a number

In [16]:
example[1,2]

5

### First 10 ages

In [17]:
age[:10]

array([28, 30, 31, 33, 19, 26, 25, 26, 37, 22])

### The last row of example

In [18]:
example[2,:]

array([6, 7, 8])

# Pandas
![pandas](pandas.jpg)

<center> O yeah </center>

The pandas library is an open source Python library, specially designed for data analysis. It has been built on NumPy and makes it easy to handle data. NumPy is a fairly low-level tool that handles matrices really well.

It's has efficient data structures to process data, perform fast joins, and read data from various sources, to name a few.

## Data series
Series is a one-dimensional array, which can hold any type of data, such as integers, floats, strings, and Python objects too. A series can be created by calling the following:

### Creating new pandas series

In [21]:
import pandas as pd

#### Without index

In [22]:
pd.Series(np.random.rand(5))

0    0.201965
1    0.880441
2    0.059213
3    0.042224
4    0.122776
dtype: float64

#### With index

In [23]:
pd.Series(np.random.rand(5), index=['a','b','c', 'd', 'e'])

a    0.276289
b    0.650503
c    0.509165
d    0.512533
e    0.418067
dtype: float64

#### Creating pandas series from a dictionary

In [24]:
data = {
    'a': 1,
    'b': 2,
    'c': 3,
    'd': 4
}

In [25]:
pd.Series(data)

a    1
b    2
c    3
d    4
dtype: int64

## Data frame
DataFrame is a 2D data structure with columns that can be of different datatypes. It
can be seen as a table. 

### Creating dataframe

#### From dictionary

In [26]:
data = {
    'a1': [1,2,3,4,5],
    'a2': ['a','b','c','d','e']
}

In [27]:
pd.DataFrame(data)

a1 a2
0   1  a
1   2  b
2   3  c
3   4  d
4   5  e

#### From data series

In [28]:
data = {
    'a1': pd.Series([1,2,3,4,5]),
    'a2': pd.Series(['a','b','c','d'])
}

In [29]:
pd.DataFrame(data)

a1   a2
0   1    a
1   2    b
2   3    c
3   4    d
4   5  NaN

## Import Pandas

In [30]:
# importing pandas
import pandas as pd

## Get our data

To get csv use `pd.read_csv`  
To get xlsx(excel) format, use `pd.read_excel`  
To get data from database 
* `pd.read_sql_table`
* `pd.read_sql_query`

In [62]:
salaries = pd.read_csv('nba_salaries.csv')

## Show data

In [65]:
salaries.head(10)

RANK           PLAYER POSITION                   TEAM  SALARY ($M)
0     1      Kobe Bryant       SF     Los Angeles Lakers    25.000000
1     2      Joe Johnson       SF          Brooklyn Nets    24.894863
2     3     LeBron James       SF    Cleveland Cavaliers    22.970500
3     4  Carmelo Anthony       SF        New York Knicks    22.875000
4     5    Dwight Howard        C        Houston Rockets    22.359364
5     6       Chris Bosh       PF             Miami Heat    22.192730
6     7       Chris Paul       PG   Los Angeles Clippers    21.468695
7     8     Kevin Durant       SF  Oklahoma City Thunder    20.158622
8     9     Derrick Rose       PG          Chicago Bulls    20.093064
9    10      Dwyane Wade       SG             Miami Heat    20.000000

In [66]:
salaries.tail(10)

RANK                  PLAYER POSITION                  TEAM  SALARY ($M)
407   408              Jeff Ayres       PF  Los Angeles Clippers     0.111444
408   409             Erick Green       PG             Utah Jazz     0.099418
409   410         Sean Kilpatrick       SG        Denver Nuggets     0.099418
410   411           Keith Appling       PG         Orlando Magic     0.061776
411   412         Orlando Johnson       SG          Phoenix Suns     0.055722
412   413         Elliot Williams       SG     Memphis Grizzlies     0.055722
413   414            Phil Pressey       PG          Phoenix Suns     0.055722
414   415            Jordan McRae       SG          Phoenix Suns     0.049709
415   416          Cory Jefferson       PF          Phoenix Suns     0.049709
416   417  Thanasis Antetokounmpo       SF       New York Knicks     0.030888

## Limit amount to display

In [33]:
salaries.head(5)

RANK           PLAYER POSITION                 TEAM  SALARY ($M)
0     1      Kobe Bryant       SF   Los Angeles Lakers    25.000000
1     2      Joe Johnson       SF        Brooklyn Nets    24.894863
2     3     LeBron James       SF  Cleveland Cavaliers    22.970500
3     4  Carmelo Anthony       SF      New York Knicks    22.875000
4     5    Dwight Howard        C      Houston Rockets    22.359364

## Data type

In [34]:
salaries.dtypes

RANK             int64
PLAYER          object
POSITION        object
TEAM            object
SALARY ($M)    float64
dtype: object

## The columns

In [69]:
salaries.columns = ['RANK', 'PLAYER', 'POSITION', 'TEAM', 'SALARY ($M)']

In [70]:
salaries

RANK                  PLAYER POSITION                 TEAM  SALARY ($M)
0       1             Kobe Bryant       SF   Los Angeles Lakers    25.000000
1       2             Joe Johnson       SF        Brooklyn Nets    24.894863
2       3            LeBron James       SF  Cleveland Cavaliers    22.970500
3       4         Carmelo Anthony       SF      New York Knicks    22.875000
4       5           Dwight Howard        C      Houston Rockets    22.359364
..    ...                     ...      ...                  ...          ...
412   413         Elliot Williams       SG    Memphis Grizzlies     0.055722
413   414            Phil Pressey       PG         Phoenix Suns     0.055722
414   415            Jordan McRae       SG         Phoenix Suns     0.049709
415   416          Cory Jefferson       PF         Phoenix Suns     0.049709
416   417  Thanasis Antetokounmpo       SF      New York Knicks     0.030888

[417 rows x 5 columns]

## Selecting a single column

### Square bracket

In [74]:
salaries["PLAYER"].head(5)

0        Kobe Bryant
1        Joe Johnson
2       LeBron James
3    Carmelo Anthony
4      Dwight Howard
Name: PLAYER, dtype: object

### Dot

In [37]:
salaries.PLAYER.head(5)

0        Kobe Bryant
1        Joe Johnson
2       LeBron James
3    Carmelo Anthony
4      Dwight Howard
Name: PLAYER, dtype: object

## Selecting multiply roles

In [38]:
salaries[['RANK', 'PLAYER', 'SALARY ($M)']].head(10)

RANK           PLAYER  SALARY ($M)
0     1      Kobe Bryant    25.000000
1     2      Joe Johnson    24.894863
2     3     LeBron James    22.970500
3     4  Carmelo Anthony    22.875000
4     5    Dwight Howard    22.359364
5     6       Chris Bosh    22.192730
6     7       Chris Paul    21.468695
7     8     Kevin Durant    20.158622
8     9     Derrick Rose    20.093064
9    10      Dwyane Wade    20.000000

In [76]:
new_salaries = salaries.set_index('PLAYER')

In [77]:
new_salaries

RANK POSITION                 TEAM  SALARY ($M)
PLAYER                                                                 
Kobe Bryant                1       SF   Los Angeles Lakers    25.000000
Joe Johnson                2       SF        Brooklyn Nets    24.894863
LeBron James               3       SF  Cleveland Cavaliers    22.970500
Carmelo Anthony            4       SF      New York Knicks    22.875000
Dwight Howard              5        C      Houston Rockets    22.359364
...                      ...      ...                  ...          ...
Elliot Williams          413       SG    Memphis Grizzlies     0.055722
Phil Pressey             414       PG         Phoenix Suns     0.055722
Jordan McRae             415       SG         Phoenix Suns     0.049709
Cory Jefferson           416       PF         Phoenix Suns     0.049709
Thanasis Antetokounmpo   417       SF      New York Knicks     0.030888

[417 rows x 4 columns]

In [78]:
new_salaries.loc['Carmelo Anthony']

RANK                         4
POSITION                    SF
TEAM           New York Knicks
SALARY ($M)             22.875
Name: Carmelo Anthony, dtype: object

In [79]:
new_salaries.iloc[3]

RANK                         4
POSITION                    SF
TEAM           New York Knicks
SALARY ($M)             22.875
Name: Carmelo Anthony, dtype: object

## Selecting Rows

In [75]:
salaries.iloc[9]

RANK                    10
PLAYER         Dwyane Wade
POSITION                SG
TEAM            Miami Heat
SALARY ($M)             20
Name: 9, dtype: object

## Create a new column

In [80]:
salaries['SOME STUFF'] = 20
salaries.head(5)

RANK           PLAYER POSITION                 TEAM  SALARY ($M)  \
0     1      Kobe Bryant       SF   Los Angeles Lakers    25.000000   
1     2      Joe Johnson       SF        Brooklyn Nets    24.894863   
2     3     LeBron James       SF  Cleveland Cavaliers    22.970500   
3     4  Carmelo Anthony       SF      New York Knicks    22.875000   
4     5    Dwight Howard        C      Houston Rockets    22.359364   

   SOME STUFF  
0          20  
1          20  
2          20  
3          20  
4          20

In [84]:
salaries.drop(columns=['SOME STUFF'], inplace=True)

In [85]:
salaries

RANK                  PLAYER POSITION                 TEAM  SALARY ($M)
0       1             Kobe Bryant       SF   Los Angeles Lakers    25.000000
1       2             Joe Johnson       SF        Brooklyn Nets    24.894863
2       3            LeBron James       SF  Cleveland Cavaliers    22.970500
3       4         Carmelo Anthony       SF      New York Knicks    22.875000
4       5           Dwight Howard        C      Houston Rockets    22.359364
..    ...                     ...      ...                  ...          ...
412   413         Elliot Williams       SG    Memphis Grizzlies     0.055722
413   414            Phil Pressey       PG         Phoenix Suns     0.055722
414   415            Jordan McRae       SG         Phoenix Suns     0.049709
415   416          Cory Jefferson       PF         Phoenix Suns     0.049709
416   417  Thanasis Antetokounmpo       SF      New York Knicks     0.030888

[417 rows x 5 columns]

## Remove columns

In [41]:
del salaries['SOME STUFF']
salaries.head(5)

RANK           PLAYER POSITION                 TEAM  SALARY ($M)
0     1      Kobe Bryant       SF   Los Angeles Lakers    25.000000
1     2      Joe Johnson       SF        Brooklyn Nets    24.894863
2     3     LeBron James       SF  Cleveland Cavaliers    22.970500
3     4  Carmelo Anthony       SF      New York Knicks    22.875000
4     5    Dwight Howard        C      Houston Rockets    22.359364

## Engineering age

### Shape of the data

In [42]:
salaries.shape

(417, 5)

### Generate random values

In [43]:
age = np.random.randint(low=18, high=50, size=417)
age[:10]

array([32, 39, 40, 36, 41, 27, 47, 21, 32, 47])

In [44]:
age.shape

(417,)

In [45]:
age = np.random.randint(18, 50, 417)
age[:10]

array([21, 24, 23, 21, 42, 27, 49, 36, 34, 47])

In [46]:
age.shape

(417,)

In [47]:
salaries['AGE'] = age
salaries.head(5)

RANK           PLAYER POSITION                 TEAM  SALARY ($M)  AGE
0     1      Kobe Bryant       SF   Los Angeles Lakers    25.000000   21
1     2      Joe Johnson       SF        Brooklyn Nets    24.894863   24
2     3     LeBron James       SF  Cleveland Cavaliers    22.970500   23
3     4  Carmelo Anthony       SF      New York Knicks    22.875000   21
4     5    Dwight Howard        C      Houston Rockets    22.359364   42

## Create new row

#### Create new dataframe

In [48]:
data = {
    'RANK': [418],
    'PLAYER': ['Solomon Igori'],
    'TEAM':['PDC'],
    'SALARY ($M)':[30.000000]
}

#### Convert to dataframe

In [49]:
data = pd.DataFrame(data);
data

RANK         PLAYER TEAM  SALARY ($M)
0   418  Solomon Igori  PDC         30.0

In [50]:
data.append(salaries, ignore_index = True)

RANK                  PLAYER                 TEAM  SALARY ($M) POSITION  \
0     418           Solomon Igori                  PDC    30.000000      NaN   
1       1             Kobe Bryant   Los Angeles Lakers    25.000000       SF   
2       2             Joe Johnson        Brooklyn Nets    24.894863       SF   
3       3            LeBron James  Cleveland Cavaliers    22.970500       SF   
4       4         Carmelo Anthony      New York Knicks    22.875000       SF   
..    ...                     ...                  ...          ...      ...   
413   413         Elliot Williams    Memphis Grizzlies     0.055722       SG   
414   414            Phil Pressey         Phoenix Suns     0.055722       PG   
415   415            Jordan McRae         Phoenix Suns     0.049709       SG   
416   416          Cory Jefferson         Phoenix Suns     0.049709       PF   
417   417  Thanasis Antetokounmpo      New York Knicks     0.030888       SF   

      AGE  
0     NaN  
1    21.0  
2    24.0  
3    23.0  
4    21.0  
..    ...  
413  20.0  
414  30.0  
415  34.0  
416  36.0  
417  35.0  

[418 rows x 6 columns]

## Delete row

In [51]:
salaries = salaries.drop(0, axis=0)
salaries

RANK                  PLAYER POSITION                 TEAM  SALARY ($M)  \
1       2             Joe Johnson       SF        Brooklyn Nets    24.894863   
2       3            LeBron James       SF  Cleveland Cavaliers    22.970500   
3       4         Carmelo Anthony       SF      New York Knicks    22.875000   
4       5           Dwight Howard        C      Houston Rockets    22.359364   
5       6              Chris Bosh       PF           Miami Heat    22.192730   
..    ...                     ...      ...                  ...          ...   
412   413         Elliot Williams       SG    Memphis Grizzlies     0.055722   
413   414            Phil Pressey       PG         Phoenix Suns     0.055722   
414   415            Jordan McRae       SG         Phoenix Suns     0.049709   
415   416          Cory Jefferson       PF         Phoenix Suns     0.049709   
416   417  Thanasis Antetokounmpo       SF      New York Knicks     0.030888   

     AGE  
1     24  
2     23  
3     21  
4     42  
5     27  
..   ...  
412   20  
413   30  
414   34  
415   36  
416   35  

[416 rows x 6 columns]

In [54]:
salaries.drop(1, axis=0, inplace=True)

In [88]:
salaries.groupby(['POSITION']).mean()[['SALARY ($M)']]

SALARY ($M)
POSITION             
C            6.082913
PF           4.951344
PG           5.165487
SF           5.532675
SG           3.988195

In [59]:
salaries.groupby(['TEAM','POSITION']).sum()[['SALARY ($M)']]

SALARY ($M)
TEAM               POSITION             
Atlanta Hawks      C           22.756250
                   PF          22.004992
                   PG           9.763400
                   SF           6.000000
                   SG           9.048461
...                                  ...
Washington Wizards C           26.217391
                   PF          15.740000
                   PG          20.161415
                   SF          16.571700
                   SG          11.356992

[147 rows x 1 columns]

In [90]:
salaries.pivot_table(index=['TEAM'], columns=['POSITION'], values=['SALARY ($M)'], aggfunc=np.mean)

SALARY ($M)                                           
POSITION                         C         PF         PG         SF        SG
TEAM                                                                         
Atlanta Hawks             7.585417  11.002496   4.881700   3.000000  1.809692
Boston Celtics            2.450465   3.085480   4.974651   4.417161  2.007554
Brooklyn Nets             1.362897   4.452514   3.900000  13.040323  1.741178
Charlotte Hornets         6.772240   4.685770   4.485304   3.766422  4.042384
Chicago Bulls            10.424380   3.467443  11.171532   1.958160  6.194465
Cleveland Cavaliers       7.752343  19.689000   6.551592  22.970500  8.988765
Dallas Mavericks          3.235482  11.913507   4.418183  15.361500  1.215174
Denver Nuggets            2.616305   7.024978   3.723620   7.195773  0.841949
Detroit Pistons           4.090697        NaN  13.913044   1.716216  4.580880
Golden State Warriors     6.541249   7.186367   8.457256   4.496695  9.000500
Houston Rockets          22.359364   1.755114   9.445491   4.919715  9.058536
Indiana Pacers            4.000000   2.471595   4.003513   6.968303  5.700000
Los Angeles Clippers      1.100602   9.509585   8.509072   2.238301  3.190104
Los Angeles Lakers        8.286783   2.253023   5.103120  10.306390  7.000000
Memphis Grizzlies         9.899722   3.364087   4.225987   5.709390  2.676720
Miami Heat                     NaN  10.197132   7.654046   3.564757  7.123384
Milwaukee Bucks           2.109294   4.047830   3.415350   1.319653  8.144347
Minnesota Timberwolves    6.426013   4.796280   5.376813   1.603210  6.421840
New Orleans Pelicans      4.850122   6.140243   3.830596   1.934208  8.806167
New York Knicks          12.650000   3.379299   3.283336   8.180910  4.422529
Oklahoma City Thunder     9.343270   5.821013   7.255246   6.522154  3.207058
Orlando Magic            11.250000   5.389060   3.051608  16.000000  3.740735
Philadelphia 76ers        4.604820   3.467184   2.144772   3.983638  1.769094
Phoenix Suns              8.403560   2.194903   3.592017   3.770540  0.869973
Portland Trail Blazers    4.470774   2.079564   4.236287   5.468477  2.124524
Sacramento Kings          8.983410        NaN   7.256780   5.562825  3.410876
San Antonio Spurs         4.650000  10.594093   5.987908   6.245388  6.407000
Toronto Raptors           3.105494   3.048442   4.756891   6.225972  5.350000
Utah Jazz                 1.674385   2.654025   1.973742   6.146973  3.779006
Washington Wizards        8.739130   5.246667   6.720472   4.142925  2.839248

# Conclusion